"""Populate training.db with an IT Business Analyst onboarding course.

The seed is idempotent for records belonging to the course: it refreshes the
course, its modules, its activities and the SQL training schema without
modifying learning events or assessment attempts stored for users.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent / "training.db"
COURSE_ID = "course_it_ba_onboarding_v1"
SCHEMA_ID = "schema_it_ba_banking_v1"

SQL_SCHEMA = """
CREATE TABLE clients (client_id TEXT PRIMARY KEY, full_name TEXT NOT NULL, segment TEXT NOT NULL, country_code TEXT NOT NULL, monthly_turnover INTEGER NOT NULL);
CREATE TABLE products (product_id TEXT PRIMARY KEY, product_name TEXT NOT NULL, card_type TEXT NOT NULL, network TEXT NOT NULL, category TEXT NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE price_levels (price_level_id TEXT PRIMARY KEY, price_level_name TEXT NOT NULL, offer_type TEXT NOT NULL, eligible_segment TEXT, status TEXT NOT NULL);
CREATE TABLE tariffs (price_level_id TEXT NOT NULL, product_id TEXT NOT NULL, monthly_fee INTEGER NOT NULL, annual_fee INTEGER NOT NULL, currency TEXT NOT NULL);
CREATE TABLE client_cards (card_id TEXT PRIMARY KEY, client_id TEXT NOT NULL, product_id TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE card_applications (application_id TEXT PRIMARY KEY, client_id TEXT NOT NULL, product_id TEXT NOT NULL, price_level_id TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE restrictions (restriction_id TEXT PRIMARY KEY, country_code TEXT NOT NULL, allowed_product_id TEXT NOT NULL, rule_description TEXT NOT NULL, status TEXT NOT NULL);
INSERT INTO clients VALUES
('C001','Ani Mkrtchyan','Persona','AM',2500000),('C002','Arman Petrosyan','Student','AM',180000),('C003','Sara Haddad','Standard','SY',400000),('C004','David Grigoryan','Pension','AM',120000),('C005','Lilit Karapetyan','Salary','AM',950000),('C006','Mariam Sargsyan','Standard','AM',310000);
INSERT INTO products VALUES
('P01','Visa Classic AMD Debit','Debit','Visa','Classic','AMD','active'),('P02','Mastercard Gold AMD Debit','Debit','Mastercard','Gold','AMD','active'),('P03','Visa Gold USD Credit','Credit','Visa','Gold','USD','active'),('P04','Arca Standard AMD Debit','Debit','Arca','Standard','AMD','active'),('P05','Visa Student AMD Debit','Debit','Visa','Student','AMD','active'),('P06','Visa Pension AMD Debit','Debit','Visa','Pension','AMD','active');
INSERT INTO price_levels VALUES
('PL_BASE','Base tariff','standard',NULL,'active'),('PL_PERSONA','Persona offer','persona','Persona','active'),('PL_STUDENT','Student offer','student','Student','active'),('PL_SALARY','Salary offer','salary','Salary','active'),('PL_PENSION','Pension offer','pension','Pension','active');
INSERT INTO tariffs VALUES
('PL_BASE','P01',1200,12000,'AMD'),('PL_BASE','P02',3000,30000,'AMD'),('PL_BASE','P03',18,180,'USD'),('PL_BASE','P04',500,5000,'AMD'),('PL_BASE','P05',700,7000,'AMD'),('PL_BASE','P06',400,4000,'AMD'),('PL_PERSONA','P02',0,0,'AMD'),('PL_PERSONA','P03',5,50,'USD'),('PL_STUDENT','P05',0,0,'AMD'),('PL_SALARY','P01',0,0,'AMD'),('PL_SALARY','P02',1000,10000,'AMD'),('PL_PENSION','P06',0,0,'AMD');
INSERT INTO client_cards VALUES
('CARD001','C001','P02','active'),('CARD002','C002','P05','active'),('CARD003','C004','P06','active'),('CARD004','C005','P01','closed'),('CARD005','C005','P02','active');
INSERT INTO card_applications VALUES
('APP001','C001','P03','PL_PERSONA','draft','2026-05-01'),('APP002','C002','P05','PL_STUDENT','submitted','2026-05-03'),('APP003','C005','P02','PL_SALARY','approved','2026-05-05'),('APP004','C006','P01','PL_BASE','draft','2026-05-06');
INSERT INTO restrictions VALUES ('R001','SY','P04','For clients from SY only Arca Standard AMD Debit is available','active');
"""

COURSE = (COURSE_ID, "IT Business Analyst: onboarding и рабочая библиотека", "Практический курс: сбор и постановка требований, процессы и данные, микросервисы, REST/SOAP и SQL SELECT с итоговым assessment на 3 часа.", "Business Analysis / Systems Analysis", "Foundation → Junior IT BA", 10, 70, "active")

MODULES = [
    ("itba_m01_role", COURSE_ID, "1. Роль IT BA и системное мышление", "Потребность, ценность, scope, stakeholder и доказательство результата.", 1, "active", "learning", None, None, None, None, None, None),
    ("itba_m02_elicitation", COURSE_ID, "2. Сбор требований и discovery", "Интервью, воркшопы, вопросы, решения и open questions.", 2, "active", "learning", None, None, None, None, None, None),
    ("itba_m03_requirements", COURSE_ID, "3. Формализация и постановка требований", "User story, business rules, FR/NFR, AC и traceability.", 3, "active", "learning", None, None, None, None, None, None),
    ("itba_m04_process_data", COURSE_ID, "4. Процессы, данные и постановка для разработки", "As-is/to-be, data dictionary, mapping и тестовые сценарии.", 4, "active", "learning", None, None, None, None, None, None),
    ("itba_m05_integrations", COURSE_ID, "5. Микросервисы, REST и SOAP", "Границы сервиса, API contract, HTTP/SOAP и обработка ошибок.", 5, "active", "learning", None, None, None, None, None, None),
    ("itba_m06_sql_select", COURSE_ID, "6. SQL SELECT: выборка, фильтры и агрегаты", "Только чтение данных: SELECT, WHERE, ORDER BY, COUNT и GROUP BY.", 6, "active", "learning", None, None, None, None, None, None),
    ("itba_m07_sql_joins", COURSE_ID, "7. SQL JOIN: связи между данными", "INNER JOIN и LEFT JOIN на клиенте, карте, продукте и тарифе.", 7, "active", "learning", None, None, None, None, None, None),
    ("itba_m08_sql_subqueries", COURSE_ID, "8. SQL подзапросы и аналитические проверки", "IN, EXISTS и NOT EXISTS для контроля бизнес-правил.", 8, "active", "learning", None, None, None, None, None, None),
    ("itba_m09_case", COURSE_ID, "9. Сквозной кейс: выдача карты и тарифное предложение", "От бизнес-запроса до API, правил, данных и проверки результата.", 9, "active", "learning", None, None, None, None, None, None),
    ("itba_m10_assessment", COURSE_ID, "10. Assessment: Requirements, API & SQL — 3 часа", "Итоговая проверка: автоматические задания и две ручные аналитические постановки.", 10, "active", "assessment", 1, 70, "mixed", "True", "True", 180),
]

ACTIVITIES: list[tuple] = []

def activity(activity_id, module_id, activity_type, title, content="", config=None, order=1, points=None, manual=None):
    ACTIVITIES.append((activity_id, COURSE_ID, module_id, activity_type, title, content, json.dumps(config or {}, ensure_ascii=False), order, "active", "{}", points, manual))

def sql_config(instructions, query, rows):
    return {"instructions": instructions, "databaseSchemaId": SCHEMA_ID, "defaultQuery": query, "validation": {"expectedRows": rows}}

activity("itba_a0101", "itba_m01_role", "html_content", "IT BA как связующее звено", """
<h2>IT Business Analyst: что он делает</h2>
<p>IT BA переводит бизнес-потребность в проверяемое изменение системы. Его результат — согласованное понимание: <b>какая проблема</b> решается, <b>для кого</b>, <b>каким поведением системы</b> и <b>как подтвердить</b>, что решение работает.</p>
<h3>Опорная цепочка</h3><ol><li><b>Need</b>: боль, возможность или обязательство.</li><li><b>Stakeholders</b>: пользователи, owners, support, compliance и команды интеграций.</li><li><b>Value</b>: эффект или снижение риска.</li><li><b>Solution scope</b>: изменения процесса, UI, данных и интеграций.</li><li><b>Evidence</b>: acceptance criteria, тестовые данные и метрики.</li></ol>
<p>Базовые артефакты: stakeholder map, user story/use case, business rules, AC, data dictionary, API request/response examples, SQL-проверки и traceability.</p>
<blockquote>До описания endpoint или поля сформулируйте бизнес-решение, которое оно поддерживает.</blockquote>
<p>Источник для дальнейшего чтения: <a href="https://www.iiba.org/career-resources/a-business-analysis-professionals-foundation-for-success/babok/">IIBA — BABOK Guide overview</a>.</p>""", order=1)
activity("itba_a0102", "itba_m01_role", "drag_mapping", "Артефакт → назначение", config={"leftTitle":"Артефакт","rightTitle":"Назначение","leftItems":["Stakeholder map","Acceptance criteria","API example","Data dictionary"],"rightItems":["Кто влияет на решение","Проверяемые условия готовности","Однозначный интеграционный обмен","Значение, тип и источник поля"],"correctMapping":{"Stakeholder map":"Кто влияет на решение","Acceptance criteria":"Проверяемые условия готовности","API example":"Однозначный интеграционный обмен","Data dictionary":"Значение, тип и источник поля"}}, order=2)
activity("itba_a0103", "itba_m01_role", "practice_quiz", "Проверка: роль аналитика", config={"questions":[{"question":"Что нужно определить до проектирования API?","options":["Потребность и ожидаемую ценность","Только HTTP status","Только таблицу","Цвет кнопки"],"correctAnswers":[0]},{"question":"Что делает требование проверяемым?","options":["Acceptance criteria и ожидаемый результат","Длинный текст","Количество встреч","Только оценка"],"correctAnswers":[0]},{"question":"Что связывает interface и данные?","options":["API example и data mapping","Только roadmap","Логотип","Meeting title"],"correctAnswers":[0]}]}, order=3)

activity("itba_a0201", "itba_m02_elicitation", "html_content", "Discovery и elicitation", """
<h2>Сбор требований — исследование решения</h2><p>На discovery аналитик уточняет контекст, ограничения, источники данных и критерии решения. Запрос пользователя может скрывать несколько ролей и исключений.</p>
<h3>До встречи</h3><ul><li>зафиксируйте цель и проблему;</li><li>составьте stakeholder map;</li><li>соберите текущие процессы, экраны, API и неизвестные вопросы;</li><li>определите ожидаемый результат встречи.</li></ul>
<h3>Вопросы</h3><ul><li>Какое решение пользователь не может принять сейчас?</li><li>При каких условиях результат нельзя показывать?</li><li>Из какой системы берётся атрибут и когда он актуален?</li><li>Что происходит при timeout или отсутствии данных?</li></ul>
<p>После встречи разделите записи на <b>confirmed decisions</b>, <b>assumptions</b>, <b>open questions</b> и action items.</p>""", order=1)
activity("itba_a0202", "itba_m02_elicitation", "drag_order", "Цикл сбора требований", config={"question":"Расположите шаги discovery","correctOrder":["Определить цель и стейкхолдеров","Собрать контекст и вопросы","Провести elicitation и записать решения","Проверить понимание и открытые вопросы","Сформировать требования и критерии"]}, order=2)
activity("itba_a0203", "itba_m02_elicitation", "practice_quiz", "Проверка: elicitation", config={"questions":[{"question":"Как оформить непрояснённое правило?","options":["Как open question с owner","Как подтверждённое","Удалить","Передать устно"],"correctAnswers":[0]},{"question":"Какой вопрос раскрывает негативный сценарий?","options":["Что делать, если сервис недоступен?","Какой цвет?","Когда встреча?","Кто писал код?"],"correctAnswers":[0]},{"question":"Что подтвердить после workshop?","options":["Решения, вопросы и действия","Только участников","Только дату","Только оценку"],"correctAnswers":[0]}]}, order=3)

activity("itba_a0301", "itba_m03_requirements", "html_content", "Постановка, которую можно реализовать и протестировать", """
<h2>Уровни требований</h2><ul><li><b>Business</b> — зачем требуется изменение.</li><li><b>Stakeholder</b> — потребность роли.</li><li><b>Functional</b> — что система должна делать.</li><li><b>Non-functional</b> — скорость, безопасность, аудит, доступность.</li><li><b>Transition</b> — миграция и ввод в эксплуатацию.</li></ul>
<h3>Структура задачи</h3><ol><li>Context и goal.</li><li>User story или use case.</li><li>Scope/out of scope.</li><li>Rules и исключения.</li><li>UI/API/data changes с полями и примерами.</li><li>AC в Given/When/Then.</li><li>Dependencies, assumptions, questions.</li></ol>
<p><b>Пример:</b> Given клиент подпадает под restriction, When система получает продукты, Then возвращается только allowed product.</p>""", order=1)
activity("itba_a0302", "itba_m03_requirements", "drag_mapping", "Тип требования → пример", config={"leftTitle":"Тип","rightTitle":"Пример","leftItems":["Business","Functional","Non-functional","Transition"],"rightItems":["Снизить ручную проверку предложений","Endpoint возвращает доступные offers","Ответ логируется с correlationId","Перед запуском загрузить restrictions"],"correctMapping":{"Business":"Снизить ручную проверку предложений","Functional":"Endpoint возвращает доступные offers","Non-functional":"Ответ логируется с correlationId","Transition":"Перед запуском загрузить restrictions"}}, order=2)
activity("itba_a0303", "itba_m03_requirements", "practice_quiz", "Проверка: AC и traceability", config={"questions":[{"question":"Что должно быть в AC?","options":["Проверяемый результат при условии","Только title","Только реализация","Только дата"],"correctAnswers":[0]},{"question":"Какое требование NFR?","options":["Ответ API до 2 секунд для 95% запросов","Создать заявку","Показать тариф","Вернуть P01"],"correctAnswers":[0]},{"question":"Что повышает traceability?","options":["Связь goal → requirement → AC → test","Удаление ID","Отказ от JSON","Больше чатов"],"correctAnswers":[0]}]}, order=3)

activity("itba_a0401", "itba_m04_process_data", "html_content", "Процесс, бизнес-правила и данные", """
<h2>Постановка должна покрывать путь решения</h2><p>Событие → проверка → business rule → данные → результат → обработка ошибки.</p>
<table><tr><th>Слой</th><th>Что фиксировать</th></tr><tr><td>Process</td><td>Actor, trigger, happy path, alternatives</td></tr><tr><td>Rule</td><td>Условие и эффект</td></tr><tr><td>Data</td><td>Field, source, type, nullable, mapping</td></tr><tr><td>Integration</td><td>Contract, errors, timeout</td></tr><tr><td>Test</td><td>Input и observable result</td></tr></table>
<p>Для каждого поля опишите business meaning, source of truth, type, mandatory/optional, validations и поведение при отсутствии значения. Для enum фиксируйте code и label.</p>""", order=1)
activity("itba_a0402", "itba_m04_process_data", "drag_order", "От правила к постановке", config={"question":"Новый restriction для продукта: что делать сначала?","correctOrder":["Уточнить условие и исключения","Определить источники client attributes","Описать правило и данные настройки","Описать API/UI и ошибки","Сформулировать AC и тестовые примеры"]}, order=2)
activity("itba_a0403", "itba_m04_process_data", "practice_quiz", "Проверка: process и data", config={"questions":[{"question":"Что такое source of truth?","options":["Система с актуальным значением поля","Скриншот","Название встречи","Комментарий"],"correctAnswers":[0]},{"question":"Что важно для enum?","options":["Code и display label","Цвет","Размер файла","Автор"],"correctAnswers":[0]},{"question":"Зачем фиксировать out of scope?","options":["Уточнить границы изменения","Не писать AC","Не тестировать","Скрыть ошибки"],"correctAnswers":[0]}]}, order=3)

activity("itba_a0501", "itba_m05_integrations", "html_content", "Микросервисы и контракты", """
<h2>Интеграция начинается с смысла</h2><p>Сервис владеет бизнес-возможностью и контрактом. Аналитик определяет владельца данных, синхронность, идемпотентность, аудит, timeout и ошибки.</p>
<h3>REST / HTTP API</h3><ul><li>ресурс и операция;</li><li>path/query/header/body, типы и validations;</li><li>response model и examples;</li><li>HTTP status и business error codes;</li><li>correlationId, retry и duplicate handling.</li></ul>
<p><b>OpenAPI</b> описывает HTTP API в language-agnostic форме: <a href="https://spec.openapis.org/oas/latest.html">official OpenAPI specification</a>.</p>
<h3>SOAP</h3><p>SOAP message использует XML Envelope, Header, Body и Fault. В enterprise-постановке нужны operation, WSDL/XSD, namespaces и fault mapping. Источник: <a href="https://www.w3.org/TR/soap12-part1/">W3C SOAP 1.2</a>.</p>
<pre>GET /api/v1/card-offers?clientId=C002&amp;currency=AMD
200 { "offers": [{ "priceLevelId":"PL_STUDENT", "productId":"P05", "monthlyFee":0, "currency":"AMD" }] }</pre>""", order=1)
activity("itba_a0502", "itba_m05_integrations", "drag_mapping", "Контракт → аналитическое уточнение", config={"leftTitle":"Элемент","rightTitle":"Что уточнить","leftItems":["GET request","POST creation","HTTP 409","SOAP Fault","correlationId"],"rightItems":["Фильтры и смысл списка","Идемпотентность и обязательные данные","Конфликт состояния/дубликат","XML error mapping","Трассировка запроса"],"correctMapping":{"GET request":"Фильтры и смысл списка","POST creation":"Идемпотентность и обязательные данные","HTTP 409":"Конфликт состояния/дубликат","SOAP Fault":"XML error mapping","correlationId":"Трассировка запроса"}}, order=2)
activity("itba_a0503", "itba_m05_integrations", "practice_quiz", "Проверка: REST и SOAP", config={"questions":[{"question":"Что определяет границу микросервиса?","options":["Business capability и владение данными","Цвет UI","Число таблиц","Случай"],"correctAnswers":[0]},{"question":"Что формализует HTTP API?","options":["OpenAPI description","Screenshot","Только SQL","SOAP Fault"],"correctAnswers":[0]},{"question":"Как SOAP представляет ошибку?","options":["Fault","ORDER BY","CSV","Tooltip"],"correctAnswers":[0]},{"question":"Для POST важно описать…","options":["Повторный запрос и обязательные поля","Только URL","Только success","Ничего"],"correctAnswers":[0]}]}, order=3)

activity("itba_a0601", "itba_m06_sql_select", "html_content", "SQL SELECT для аналитика", """
<h2>Только чтение данных</h2><p>Курс не включает создание/удаление баз. Вы выполняете только <code>SELECT</code>, чтобы проверять данные, правила и результаты интеграций.</p>
<pre>SELECT column_1, column_2 FROM table_name WHERE condition ORDER BY column_1;</pre>
<ul><li><code>WHERE</code> фильтрует строки.</li><li><code>DISTINCT</code> убирает повторяющиеся комбинации.</li><li><code>COUNT</code>, <code>SUM</code>, <code>MIN/MAX</code> агрегируют.</li><li><code>GROUP BY</code> определяет уровень агрегирования.</li><li><code>HAVING</code> фильтрует группы.</li></ul>
<p>Сначала назовите единицу результата: клиент, карта или offer. Документация: <a href="https://www.sqlite.org/lang_select.html">SQLite SELECT</a>.</p>""", order=1)
activity("itba_a0602", "itba_m06_sql_select", "sql_practice", "SQL 1: фильтрация клиентов", config=sql_config("Верните client_id, full_name, segment клиентов Student, сортировка по full_name.", "SELECT client_id, full_name, segment FROM clients WHERE segment = 'Student' ORDER BY full_name;", [{"client_id":"C002","full_name":"Arman Petrosyan","segment":"Student"}]), order=2)
activity("itba_a0603", "itba_m06_sql_select", "sql_practice", "SQL 2: группировка карт", config=sql_config("Посчитайте карты по статусам: status, card_count; сортировка по status.", "SELECT status, COUNT(*) AS card_count FROM client_cards GROUP BY status ORDER BY status;", [{"status":"active","card_count":4},{"status":"closed","card_count":1}]), order=3)
activity("itba_a0604", "itba_m06_sql_select", "sql_practice", "SQL 3: базовые тарифы", config=sql_config("Найдите AMD-тарифы PL_BASE с monthly_fee <= 1200. Верните product_id, monthly_fee, currency; сортировка по fee и id.", "SELECT product_id, monthly_fee, currency FROM tariffs WHERE price_level_id = 'PL_BASE' AND currency = 'AMD' AND monthly_fee <= 1200 ORDER BY monthly_fee, product_id;", [{"product_id":"P06","monthly_fee":400,"currency":"AMD"},{"product_id":"P04","monthly_fee":500,"currency":"AMD"},{"product_id":"P05","monthly_fee":700,"currency":"AMD"},{"product_id":"P01","monthly_fee":1200,"currency":"AMD"}]), order=4)
activity("itba_a0605", "itba_m06_sql_select", "practice_quiz", "Проверка: SELECT", config={"questions":[{"question":"Что фильтрует строки до GROUP BY?","options":["WHERE","ORDER BY","Alias","Create"],"correctAnswers":[0]},{"question":"Одна строка GROUP BY status — это…","options":["Один status и агрегаты","Одна карта","Один API","Одна БД"],"correctAnswers":[0]},{"question":"Зачем ORDER BY в проверяемой выдаче?","options":["Предсказуемый порядок","Создание таблицы","Изменение данных","Удаление строк"],"correctAnswers":[0]}]}, order=5)

activity("itba_a0701", "itba_m07_sql_joins", "html_content", "JOIN и кардинальность", """
<h2>Соединяем сущности по бизнес-вопросу</h2><p>Данные о client, card, product и tariff разделены. <b>INNER JOIN</b> сохраняет совпавшие записи; <b>LEFT JOIN</b> сохраняет все строки слева, даже без соответствия.</p>
<p>Перед JOIN проверьте кардинальность: один client имеет несколько cards, один product — несколько tariffs по price levels. Без ограничения price level строки будут дублироваться.</p>
<pre>SELECT c.full_name, p.product_name FROM clients c JOIN client_cards cc ON cc.client_id=c.client_id JOIN products p ON p.product_id=cc.product_id WHERE cc.status='active';</pre>""", order=1)
activity("itba_a0702", "itba_m07_sql_joins", "drag_mapping", "JOIN → применение", config={"leftTitle":"Вопрос","rightTitle":"Подход","leftItems":["Только клиенты с active card","Все продукты без salary tariff","Название продукта для карты","Исключить дубли price levels"],"rightItems":["INNER JOIN и status filter","LEFT JOIN и NULL check","JOIN по product_id","Фильтр price_level_id"],"correctMapping":{"Только клиенты с active card":"INNER JOIN и status filter","Все продукты без salary tariff":"LEFT JOIN и NULL check","Название продукта для карты":"JOIN по product_id","Исключить дубли price levels":"Фильтр price_level_id"}}, order=2)
activity("itba_a0703", "itba_m07_sql_joins", "sql_practice", "SQL 4: активные карты", config=sql_config("Верните full_name, product_name, status активных карт; сортировка по full_name.", "SELECT c.full_name, p.product_name, cc.status FROM clients c JOIN client_cards cc ON cc.client_id=c.client_id JOIN products p ON p.product_id=cc.product_id WHERE cc.status='active' ORDER BY c.full_name;", [{"full_name":"Ani Mkrtchyan","product_name":"Mastercard Gold AMD Debit","status":"active"},{"full_name":"Arman Petrosyan","product_name":"Visa Student AMD Debit","status":"active"},{"full_name":"David Grigoryan","product_name":"Visa Pension AMD Debit","status":"active"},{"full_name":"Lilit Karapetyan","product_name":"Mastercard Gold AMD Debit","status":"active"}]), order=3)
activity("itba_a0704", "itba_m07_sql_joins", "sql_practice", "SQL 5: продукты без salary tariff", config=sql_config("LEFT JOIN: верните product_id, product_name продуктов без PL_SALARY; сортировка по product_id.", "SELECT p.product_id, p.product_name FROM products p LEFT JOIN tariffs t ON t.product_id=p.product_id AND t.price_level_id='PL_SALARY' WHERE t.product_id IS NULL ORDER BY p.product_id;", [{"product_id":"P03","product_name":"Visa Gold USD Credit"},{"product_id":"P04","product_name":"Arca Standard AMD Debit"},{"product_id":"P05","product_name":"Visa Student AMD Debit"},{"product_id":"P06","product_name":"Visa Pension AMD Debit"}]), order=4)
activity("itba_a0705", "itba_m07_sql_joins", "sql_practice", "SQL 6: Student offer", config=sql_config("Верните price_level_name, product_name, monthly_fee, currency для offer_type='student'.", "SELECT pl.price_level_name, p.product_name, t.monthly_fee, t.currency FROM tariffs t JOIN price_levels pl ON pl.price_level_id=t.price_level_id JOIN products p ON p.product_id=t.product_id WHERE pl.offer_type='student' ORDER BY p.product_id;", [{"price_level_name":"Student offer","product_name":"Visa Student AMD Debit","monthly_fee":0,"currency":"AMD"}]), order=5)

activity("itba_a0801", "itba_m08_sql_subqueries", "html_content", "Подзапросы для проверок", """
<h2>EXISTS и NOT EXISTS</h2><p>Подзапрос отвечает на вопросы существования связи: клиенты без active cards, продукты из restrictions, клиенты под ограничением.</p>
<pre>SELECT c.client_id, c.full_name FROM clients c WHERE NOT EXISTS (SELECT 1 FROM client_cards cc WHERE cc.client_id=c.client_id AND cc.status='active');</pre>
<p><code>IN (SELECT ...)</code> удобен для набора identifiers. Scalar subquery должен вернуть одно значение. Для читаемых многошаговых выборок изучите <a href="https://www.sqlite.org/lang_with.html">SQLite WITH</a>.</p>""", order=1)
activity("itba_a0802", "itba_m08_sql_subqueries", "sql_practice", "SQL 7: клиенты без active card", config=sql_config("Используйте NOT EXISTS. Верните client_id, full_name; сортировка по client_id.", "SELECT c.client_id, c.full_name FROM clients c WHERE NOT EXISTS (SELECT 1 FROM client_cards cc WHERE cc.client_id=c.client_id AND cc.status='active') ORDER BY c.client_id;", [{"client_id":"C003","full_name":"Sara Haddad"},{"client_id":"C006","full_name":"Mariam Sargsyan"}]), order=2)
activity("itba_a0803", "itba_m08_sql_subqueries", "sql_practice", "SQL 8: allowed products в restrictions", config=sql_config("Верните product_id, product_name продуктов, указанных как allowed_product_id в active restrictions.", "SELECT product_id, product_name FROM products WHERE product_id IN (SELECT allowed_product_id FROM restrictions WHERE status='active') ORDER BY product_id;", [{"product_id":"P04","product_name":"Arca Standard AMD Debit"}]), order=3)
activity("itba_a0804", "itba_m08_sql_subqueries", "sql_practice", "SQL 9: клиенты под restriction", config=sql_config("Используйте EXISTS. Верните client_id, full_name, country_code клиентов с active restriction.", "SELECT c.client_id, c.full_name, c.country_code FROM clients c WHERE EXISTS (SELECT 1 FROM restrictions r WHERE r.country_code=c.country_code AND r.status='active') ORDER BY c.client_id;", [{"client_id":"C003","full_name":"Sara Haddad","country_code":"SY"}]), order=4)
activity("itba_a0805", "itba_m08_sql_subqueries", "practice_quiz", "Проверка: подзапросы", config={"questions":[{"question":"Как найти отсутствие active card?","options":["NOT EXISTS","ORDER BY","DELETE","CREATE"],"correctAnswers":[0]},{"question":"Что проверить перед scalar subquery?","options":["Он возвращает максимум одно значение","Цвет","Шрифт","IDE"],"correctAnswers":[0]},{"question":"Зачем CTE?","options":["Сделать многошаговую проверку читаемой","Удалить данные","Создать API","Изменить UI"],"correctAnswers":[0]}]}, order=5)

activity("itba_a0901", "itba_m09_case", "html_content", "Кейс: offers для карточной операции", """
<h2>Business context</h2><p>Сотрудник открывает карту. Система показывает только допустимые продукты и тарифные предложения, чтобы исключить нарушение restrictions и неверный offer.</p>
<h3>Rules</h3><ol><li>Базовый список определяется параметрами продукта.</li><li>Special price level применяется при совпадении segment.</li><li>Active country restriction ограничивает список allowed_product_id.</li><li>При недоступности offer service UI показывает ошибку и не подтверждает выбор.</li></ol>
<h3>Артефакты BA</h3><ul><li>REST contract и JSON examples;</li><li>mapping segment/country/product/tariff/restriction;</li><li>AC для normal, restriction и failure paths;</li><li>SQL checks для UAT.</li></ul>
<p><b>AC example:</b> Given C003 has country_code SY and R001 is active, When products are requested, Then only P04 is returned.</p>""", order=1)
activity("itba_a0902", "itba_m09_case", "drag_order", "Порядок анализа кейса", config={"question":"Расставьте шаги","correctOrder":["Подтвердить цель и eligibility rules","Зафиксировать sources client/product/tariff/restriction","Определить API contract и errors","Подготовить SQL checks и test data","Сформулировать acceptance criteria"]}, order=2)
activity("itba_a0903", "itba_m09_case", "sql_practice", "Кейс SQL: Student offer", config=sql_config("Для C002 найдите специальное предложение в AMD: product_id, product_name, monthly_fee, currency.", "SELECT p.product_id, p.product_name, t.monthly_fee, t.currency FROM clients c JOIN price_levels pl ON pl.eligible_segment=c.segment AND pl.status='active' JOIN tariffs t ON t.price_level_id=pl.price_level_id JOIN products p ON p.product_id=t.product_id WHERE c.client_id='C002' AND p.currency='AMD' ORDER BY p.product_id;", [{"product_id":"P05","product_name":"Visa Student AMD Debit","monthly_fee":0,"currency":"AMD"}]), order=3)
activity("itba_a0904", "itba_m09_case", "practice_quiz", "Проверка: сквозной анализ", config={"questions":[{"question":"Какое правило приоритетно для C003/SY?","options":["Active restriction","Случайный tariff","Последняя страница","Все продукты"],"correctAnswers":[0]},{"question":"Что описать при недоступности offers service?","options":["UI error и невозможность подтвердить ошибочный выбор","Только URL","Только happy path","Ничего"],"correctAnswers":[0]},{"question":"Что подтверждает реализуемость requirement?","options":["Rule + source fields + API + AC + test data","Meeting title","Label","Цвет"],"correctAnswers":[0]}]}, order=4)

# Timed assessment: suggested allocation 20 + 25 + 30 + 30 + 40 + 35 = 180 minutes; total points = 100.
activity("itba_as01", "itba_m10_assessment", "quiz", "Часть 1. Теория — 20 минут / 20 баллов", config={"intro":"12 вопросов. Выберите лучший ответ.","questions":[{"question":"Что определить до solution requirement?","options":["Need, stakeholders, value","Только table","Только HTTP 200","Color"],"correctAnswers":[0]},{"question":"Какое требование NFR?","options":["API логирует correlationId и отвечает до 2 секунд для 95% запросов","Показать offers","Создать application","Вернуть productId"],"correctAnswers":[0]},{"question":"Как управлять неизвестностью?","options":["Open question с owner","Скрыть предположение","Удалить scenario","Устное обещание"],"correctAnswers":[0]},{"question":"Для чего data mapping?","options":["Связать response field с source и rule","Выбрать цвет","Заменить тест","Создать repo"],"correctAnswers":[0]},{"question":"Что нужно AC?","options":["Наблюдаемый результат","Размытое пожелание","Только architecture","Только срок"],"correctAnswers":[0]},{"question":"OpenAPI описывает…","options":["HTTP API contract","Только SOAP Fault","SQL engine","Список команды"],"correctAnswers":[0]},{"question":"Ошибка SOAP — это…","options":["Fault","ORDER BY","CSV","Tooltip"],"correctAnswers":[0]},{"question":"Idempotency POST нужна для…","options":["Повторного запроса без нежелательного дубля","Выбора network","Сортировки","Удаления AC"],"correctAnswers":[0]},{"question":"Как соединить client и card?","options":["JOIN по key","ORDER BY","DISTINCT без FROM","HAVING"],"correctAnswers":[0]},{"question":"Клиенты без cards ищутся через…","options":["NOT EXISTS","LIMIT","CREATE","UPDATE"],"correctAnswers":[0]},{"question":"Перед JOIN tariffs нужно проверить…","options":["Кардинальность и price level","Размер шрифта","Число людей","Цвет"],"correctAnswers":[0]},{"question":"Active restriction приводит к…","options":["Фильтрации по allowed product","Игнорированию rule","Удалению client","Возврату всего"],"correctAnswers":[0]}]}, order=1, points=20, manual="False")
activity("itba_as02", "itba_m10_assessment", "sql_task", "Часть 2. SQL SELECT и aggregation — 25 минут / 15 баллов", config=sql_config("Верните segment и COUNT(*) AS client_count. Сортировка по segment. Только SELECT.", "SELECT -- напишите запрос здесь", [{"segment":"Pension","client_count":1},{"segment":"Persona","client_count":1},{"segment":"Salary","client_count":1},{"segment":"Standard","client_count":2},{"segment":"Student","client_count":1}]), order=2, points=15, manual="False")
activity("itba_as03", "itba_m10_assessment", "sql_task", "Часть 3. SQL JOIN и tariff — 30 минут / 15 баллов", config=sql_config("Для Persona clients с active card верните full_name, product_name, monthly_fee, currency по PL_PERSONA; сортировка по full_name, product_name.", "SELECT -- напишите запрос здесь", [{"full_name":"Ani Mkrtchyan","product_name":"Mastercard Gold AMD Debit","monthly_fee":0,"currency":"AMD"}]), order=3, points=15, manual="False")
activity("itba_as04", "itba_m10_assessment", "sql_task", "Часть 4. SQL NOT EXISTS — 30 минут / 15 баллов", config=sql_config("Верните client_id и full_name клиентов без active card. Используйте NOT EXISTS; сортировка по client_id.", "SELECT -- напишите запрос здесь", [{"client_id":"C003","full_name":"Sara Haddad"},{"client_id":"C006","full_name":"Mariam Sargsyan"}]), order=4, points=15, manual="False")
activity("itba_as05", "itba_m10_assessment", "open_answer", "Часть 5. Постановка требований — 40 минут / 20 баллов", "Сценарий: offers отображаются при выдаче карты; для country_code=SY действует restriction с единственным продуктом P04. Подготовьте business goal, user story, scope, rules, минимум 4 AC в Given/When/Then (normal, restricted, service unavailable, no suitable offer), данные и open questions.", {"placeholder":"Введите постановку и Acceptance Criteria…","minLength":900}, 5, 20, "True")
activity("itba_as06", "itba_m10_assessment", "open_answer", "Часть 6. API contract и mapping — 35 минут / 15 баллов", "Спроектируйте REST-контракт получения offers: method/endpoint, parameters, successful JSON, validation/service-failure errors, correlationId/idempotency где применимо. Добавьте mapping response fields к clients/products/price_levels/tariffs/restrictions и объясните приоритет restriction.", {"placeholder":"Опишите REST contract, JSON examples, errors и mapping…","minLength":900}, 6, 15, "True")

def seed(db_path: Path = DB_PATH) -> None:
    conn = sqlite3.connect(db_path)
    try:
        required = {"courses", "modules", "activities", "sqlSchemas"}
        actual = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        missing = required - actual
        if missing:
            raise RuntimeError(f"Database is not initialized. Missing tables: {', '.join(sorted(missing))}. Run python app.py once, then rerun this seed.")
        conn.execute("INSERT OR REPLACE INTO sqlSchemas(schemaId,title,description,initSql,status) VALUES(?,?,?,?,?)", (SCHEMA_ID, "Training bank: clients, cards, tariffs and restrictions", "SQL dataset for IT BA exercises; learners execute SELECT queries only.", SQL_SCHEMA, "active"))
        conn.execute("INSERT OR REPLACE INTO courses(courseId,title,description,category,level,displayOrder,passingScore,status) VALUES(?,?,?,?,?,?,?,?)", COURSE)
        conn.executemany("INSERT OR REPLACE INTO modules(moduleId,courseId,title,description,displayOrder,status,moduleType,maxAttempts,passingScore,reviewMode,lockAfterSubmit,isTimed,timeLimitMinutes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)", MODULES)
        conn.executemany("INSERT OR REPLACE INTO activities(activityId,courseId,moduleId,activityType,title,content,configJson,displayOrder,status,validationJson,points,manualReviewRequired) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", ACTIVITIES)
        conn.commit()
    finally:
        conn.close()
    print(f"Seeded course {COURSE_ID}: {len(MODULES)} modules, {len(ACTIVITIES)} activities, assessment time limit 180 minutes.")

if __name__ == "__main__":
    seed()
